export default [
  {
    id: 1,
    title: "Quinoa Salad with Vegetables",
    description:
      "This quinoa salad is fresh and nutritious, perfect for a light meal or as a side dish. Quinoa, rich in protein and fiber, is combined with a variety of fresh vegetables and a lemon vinaigrette.",
    preparation: {
      ingredients: "15 minutes",
      cooking: "0 minutes",
      total: "15 minutes",
    },
    instructions: [
      "Cook the quinoa in the water according to package instructions. Let it cool.",
      "In a large bowl, combine the cooked quinoa with the bell pepper, cucumber, cherry tomatoes, red onion, and parsley.",
      "In a small bowl, mix together the olive oil, lemon juice, salt, and pepper.",
      "Pour the vinaigrette over the salad and toss well.",
      "Serve immediately or refrigerate before serving.",
    ],
    ingredients: [
      "1 cup quinoa",
      "2 cups water",
      "1 red bell pepper, chopped",
      "1 cucumber, chopped",
      "1 cup cherry tomatoes, halved",
      "1/4 cup red onion, finely chopped",
      "1/4 cup fresh parsley, chopped",
      "2 tablespoons olive oil",
      "Juice of 1 lemon",
      "Salt and pepper to taste",
    ],
    nutritionalValues: {
      calories: 220,
      carbohydrates: "32g",
      protein: "6g",
      fat: "8g",
      fiber: "5g",
    },
  },
  {
    id: 2,
    title: "Rigatoni with Panko",
    description:
      "Rigatoni with Panko is a flavorful Italian dish featuring al dente pasta baked with a crispy, golden panko breadcrumb topping, often seasoned with garlic, herbs, and Parmesan.",
    preparation: {
      ingredients: "15 minutes",
      cooking: "15 minutes",
      total: "30 minutes",
    },
    instructions: [
      "Preheat Oven to 180°C (350°F). Allow it to fully heat up while you prepare the other ingredients.",
      "Cook Rigatoni in a large pot of salted boiling water until it reaches al dente, then drain and set aside.",
      "Prepare Panko Mixture by combining panko breadcrumbs with minced garlic, dried herbs, and grated Parmesan cheese in a bowl. Mix thoroughly.",
      "Combine Pasta with Sauce by mixing the cooked rigatoni with your chosen pasta sauce until evenly coated.",
      "Transfer Pasta to Baking Dish. Lightly grease a baking dish and pour the sauced pasta into it, spreading it out evenly.",
      "Add Panko Topping by sprinkling the panko mixture evenly over the top of the pasta in the dish.",
      "Bake for 15 minutes or until the panko topping is golden brown and crispy. Let it cool slightly before serving.",
    ],
    ingredients: [
      "300 grams rigatoni pasta",
      "1 cup panko breadcrumbs",
      "2 cloves garlic, minced",
      "1 teaspoon dried herbs",
      "1/2 cup Parmesan cheese, grated",
      "2 cups pasta sauce",
      "Butter or non-stick spray for greasing the baking dish",
    ],
    nutritionalValues: {
      calories: 450,
      carbohydrates: "60g",
      protein: "15g",
      fat: "18g",
      fiber: "12g",
    },
  },
  {
    id: 3,
    title: "",
    description: "",
    preparation: {
      ingredients: "",
      cooking: "",
      total: "",
    },

    instructions: ["", "", "", "", "", "", ""],
    ingredients: ["", "", "", "", "", "", ""],
    nutritionalValues: {
      calories: "",
      carbohydrates: "",
      protein: "",
      fat: "",
      fiber: "",
    },
  },
  {
    id: 4,
    title: "Spaghetti Bolognese",
    description:
      " Spaghetti Bolognese is a classic Italian dish featuring a rich, savory meat sauce served over pasta. The sauce is made with ground beef, onions, garlic, carrots, and tomatoes, simmered to perfection with herbs and spices. This hearty meal is perfect for a family dinner or a special occasion. The combination of tender meat and flavorful sauce makes it a favorite worldwide. It’s easy to prepare and can be made in large batches for leftovers. Serve it with a sprinkle of Parmesan cheese and fresh basil for an authentic Italian experience.",
    preparation: {
      ingredients: "15 minutes",
      cooking: "45 minutes",
      total: "1 hour",
    },

    instructions: [
      "Sautéing the base: 1. Heat 2 tbsp of olive oil in a large pan over medium heat. 2. Add 1 finely chopped onion and 2 minced garlic cloves. Sauté for 5-6 minutes until softened.",
      "Cooking the Meat: Add 400g of ground beef to the pan. Cook until browned, breaking it up with a spoon.",
      "Adding Vegetables and Liquids: 1. Add 100g of grated carrot and 2 cans (400g each) of chopped tomatoes. 2. Pour in 400ml of beef stock and stir well.",
      "Simmering the Sauce: Bring the mixture to a simmer. Reduce the heat and let it cook gently for 45 minutes, stirring occasionally.",
      "Cooking the Pasta: Cook 400g of spaghetti according to the package instructions. Drain and mix with the sauce. Serve hot.",
    ],
    ingredients: [
      "2 tbsp olive oil.",
      "2 garlic cloves, minced.",
      "400g ground beef.",
      "100g grated carrot.",
      "2 cans (400g each) chopped tomatoes.",
      "400ml beef stock.",
      "400ml beef stock.",
      "Salt and pepper to taste.",
    ],
    nutritionalValues: {
      calories: "787Kca.",
      carbohydrates: "103g (of which 19g sugars).",
      protein: "35g.",
      fat: "Fat: 24g (of which 8g saturates).",
      fiber: "8.5g.",
    },
  },
  {
    id: 5,
    title: "",
    description: "",
    preparation: {
      ingredients: "",
      cooking: "",
      total: "",
    },

    instructions: ["", "", "", "", "", "", ""],
    ingredients: ["", "", "", "", "", "", ""],
    nutritionalValues: {
      calories: "",
      carbohydrates: "",
      protein: "",
      fat: "",
      fiber: "",
    },
  },
];
