export default [
  {
    id: 1,
    title: "Quinoa Salad with Vegetables",
    description:
      "This quinoa salad is fresh and nutritious, perfect for a light meal or as a side dish. Quinoa, rich in protein and fiber, is combined with a variety of fresh vegetables and a lemon vinaigrette.",
    preparation: {
      ingredients: "15 minutes",
      cooking: "0 minutes",
      total: "15 minutes",
    },
    instructions: [
      "Cook the quinoa in the water according to package instructions. Let it cool.",
      "In a large bowl, combine the cooked quinoa with the bell pepper, cucumber, cherry tomatoes, red onion, and parsley.",
      "In a small bowl, mix together the olive oil, lemon juice, salt, and pepper.",
      "Pour the vinaigrette over the salad and toss well.",
      "Serve immediately or refrigerate before serving.",
    ],
    ingredients: [
      "1 cup quinoa",
      "2 cups water",
      "1 red bell pepper, chopped",
      "1 cucumber, chopped",
      "1 cup cherry tomatoes, halved",
      "1/4 cup red onion, finely chopped",
      "1/4 cup fresh parsley, chopped",
      "2 tablespoons olive oil",
      "Juice of 1 lemon",
      "Salt and pepper to taste",
    ],
    nutritionalValues: {
      calories: 220,
      carbohydrates: "32g",
      protein: "6g",
      fat: "8g",
      fiber: "5g",
    },
  },
  {
    id: 2,
    title: "Rigatoni with Panko",
    description:
      "Rigatoni with Panko is a flavorful Italian dish featuring al dente pasta baked with a crispy, golden panko breadcrumb topping, often seasoned with garlic, herbs, and Parmesan.",
    preparation: {
      ingredients: "15 minutes",
      cooking: "15 minutes",
      total: "30 minutes",
    },
    instructions: [
      "Preheat Oven to 180°C (350°F). Allow it to fully heat up while you prepare the other ingredients.",
      "Cook Rigatoni in a large pot of salted boiling water until it reaches al dente, then drain and set aside.",
      "Prepare Panko Mixture by combining panko breadcrumbs with minced garlic, dried herbs, and grated Parmesan cheese in a bowl. Mix thoroughly.",
      "Combine Pasta with Sauce by mixing the cooked rigatoni with your chosen pasta sauce until evenly coated.",
      "Transfer Pasta to Baking Dish. Lightly grease a baking dish and pour the sauced pasta into it, spreading it out evenly.",
      "Add Panko Topping by sprinkling the panko mixture evenly over the top of the pasta in the dish.",
      "Bake for 15 minutes or until the panko topping is golden brown and crispy. Let it cool slightly before serving.",
    ],
    ingredients: [
      "300 grams rigatoni pasta",
      "1 cup panko breadcrumbs",
      "2 cloves garlic, minced",
      "1 teaspoon dried herbs",
      "1/2 cup Parmesan cheese, grated",
      "2 cups pasta sauce",
      "Butter or non-stick spray for greasing the baking dish",
    ],
    nutritionalValues: {
      calories: 450,
      carbohydrates: "60g",
      protein: "15g",
      fat: "18g",
      fiber: "12g",
    },
  },
  {
    id: 3,
    title: "Orzo with Zucchini",
    description:
      "Orzo with Zucchini is a delightful Italian dish known for its light and fresh flavor. This simple yet elegant meal features tender orzo pasta cooked with crisp, sautéed zucchini and often enhanced with herbs and a hint of lemon.",
    preparation: {
      ingredients: "10 minutes",
      cooking: "20 minutes",
      total: "30 minutes",
    },
    instructions: [
      "1. Bring a large pot of salted water to a boil. Add the orzo and cook according to package instructions until al dente. Drain and set aside.",
      "2. While the orzo is cooking, heat olive oil in a large skillet over medium heat.",
      "3. Add the minced garlic and sauté for 1-2 minutes until fragrant, but not browned.",
      "4. Add the sliced zucchini to the skillet and cook for 5-7 minutes, stirring occasionally, until the zucchini is tender and slightly golden.",
      "5. Add the cooked orzo to the skillet with the zucchini and mix well.",
      "6. Stir in the grated Parmesan cheese, lemon juice, salt, and pepper. Mix until the cheese is melted and everything is well combined.",
      "7. Serve immediately, garnished with fresh basil leaves if desired.",
    ],
    ingredients: [
      "1 cup orzo pasta",
      "2 medium zucchinis, thinly sliced",
      "2 tablespoons olive oil",
      "2 cloves garlic, minced",
      "1/4 cup grated Parmesan cheese",
      "Juice of 1 lemon",
      "Salt and pepper to taste",
      "Fresh basil leaves, for garnish (optional)",
    ],
    nutritionalValues: {
      calories: "320 kcal",
      carbohydrates: "48g",
      protein: "10g",
      fat: "9g",
      fiber: "3g",
    },
  },
  {
    id: 4,
    title: "Spaghetti Bolognese",
    description:
      " Spaghetti Bolognese is a classic Italian dish featuring a rich, savory meat sauce served over pasta. The sauce is made with ground beef, onions, garlic, carrots, and tomatoes, simmered to perfection with herbs and spices. This hearty meal is perfect for a family dinner or a special occasion. The combination of tender meat and flavorful sauce makes it a favorite worldwide. It’s easy to prepare and can be made in large batches for leftovers. Serve it with a sprinkle of Parmesan cheese and fresh basil for an authentic Italian experience.",
    preparation: {
      ingredients: "15 minutes",
      cooking: "45 minutes",
      total: "1 hour",
    },
    instructions: [
      "Sautéing the base: 1. Heat 2 tbsp of olive oil in a large pan over medium heat. 2. Add 1 finely chopped onion and 2 minced garlic cloves. Sauté for 5-6 minutes until softened.",
      "Cooking the Meat: Add 400g of ground beef to the pan. Cook until browned, breaking it up with a spoon.",
      "Adding Vegetables and Liquids: 1. Add 100g of grated carrot and 2 cans (400g each) of chopped tomatoes. 2. Pour in 400ml of beef stock and stir well.",
      "Simmering the Sauce: Bring the mixture to a simmer. Reduce the heat and let it cook gently for 45 minutes, stirring occasionally.",
      "Cooking the Pasta: Cook 400g of spaghetti according to the package instructions. Drain and mix with the sauce. Serve hot.",
    ],
    ingredients: [
      "2 tbsp olive oil.",
      "2 garlic cloves, minced.",
      "400g ground beef.",
      "100g grated carrot.",
      "2 cans (400g each) chopped tomatoes.",
      "400ml beef stock.",
      "400ml beef stock.",
      "Salt and pepper to taste.",
    ],
    nutritionalValues: {
      calories: "787Kca.",
      carbohydrates: "103g (of which 19g sugars).",
      protein: "35g.",
      fat: "Fat: 24g (of which 8g saturates).",
      fiber: "8.5g.",
    },
  },
  {
    id: 5,
    title: "Shrimp Salad",
    description:
      "Shrimp Salad is a refreshing and light dish, perfect for a quick meal or a healthy side. It features succulent shrimp tossed with crisp vegetables and a tangy dressing.",
    preparation: {
      ingredients: "10 minutes",
      cooking: "10 minutes",
      total: "20 minutes",
    },
    instructions: [
      "1. Bring a pot of water to a boil. Add a pinch of salt and the shrimp. Cook for 3-4 minutes, or until the shrimp are pink and opaque. Drain and let cool.",
      "2. In a large mixing bowl, combine the cooled shrimp, diced cucumber, cherry tomatoes, red onion, and avocado.",
      "3. In a small bowl, whisk together the olive oil, lemon juice, Dijon mustard, salt, and pepper to make the dressing.",
      "4. Pour the dressing over the shrimp and vegetables, and toss gently to combine.",
      "5. Add chopped fresh dill and gently mix again.",
      "6. Serve immediately on a bed of mixed greens or chilled in the refrigerator for later.",
    ],
    ingredients: [
      "1 lb shrimp, peeled and deveined",
      "1 cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/4 cup red onion, finely chopped",
      "1 avocado, diced",
      "2 tablespoons olive oil",
      "Juice of 1 lemon",
      "1 teaspoon Dijon mustard",
      "Salt and pepper to taste",
      "1 tablespoon fresh dill, chopped",
      "Mixed greens, for serving (optional)",
    ],
    nutritionalValues: {
      calories: "280 kcal",
      carbohydrates: "12g",
      protein: "30g",
      fat: "14g",
      fiber: "6g",
    },
  },
];
